#!/usr/bin/env node

import readline from 'readline';
import { execSync } from 'child_process';
import path from 'path';
import fs from 'fs';
import os from 'os';

const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
const ask = (q: string): Promise<string> => new Promise(resolve => rl.question(q, resolve));

const TASK_NAME = 'ClaudeMaxWake';
const SCRIPTS_DIR = path.join(os.homedir(), 'scripts');
const SCRIPT_PATH = path.join(SCRIPTS_DIR, 'claude-wake.ps1');
const LOG_PATH = path.join(SCRIPTS_DIR, 'claude-wake.log');
const CONFIG_PATH = path.join(SCRIPTS_DIR, 'claude-wake.json');

interface WakeConfig {
  claudePath: string;
  configDir: string | null;
  profileName: string;
}

function banner() {
  console.log('');
  console.log('  ===================================');
  console.log('  CLAUDE WAKE - Schedule your sessions');
  console.log('  ===================================');
  console.log('');
}

function loadConfig(): WakeConfig | null {
  try {
    if (fs.existsSync(CONFIG_PATH)) {
      return JSON.parse(fs.readFileSync(CONFIG_PATH, 'utf8'));
    }
  } catch {}
  return null;
}

function saveConfig(config: WakeConfig) {
  fs.writeFileSync(CONFIG_PATH, JSON.stringify(config, null, 2), 'utf8');
}

function findClaude(): string {
  const localBin = path.join(os.homedir(), '.local', 'bin', 'claude.exe');
  if (fs.existsSync(localBin)) return localBin;

  try {
    const result = execSync('where.exe claude', { encoding: 'utf8' }).trim().split('\n')[0];
    if (result) return result.trim();
  } catch {}

  return 'claude';
}

function detectProfiles(): { name: string; configDir: string }[] {
  const homeDir = os.homedir();
  const profiles: { name: string; configDir: string }[] = [];

  // Scan for .claude* directories that have credentials
  try {
    const entries = fs.readdirSync(homeDir);
    for (const entry of entries) {
      if (entry.startsWith('.claude')) {
        const fullPath = path.join(homeDir, entry);
        const credFile = path.join(fullPath, '.credentials.json');
        if (fs.statSync(fullPath).isDirectory() && fs.existsSync(credFile)) {
          const name = entry === '.claude' ? 'claude (default)' : entry.replace('.', '');
          profiles.push({ name, configDir: fullPath });
        }
      }
    }
  } catch {}

  return profiles;
}

function generateWakeScript(claudePath: string, configDir: string | null): string {
  const configLine = configDir
    ? `    $env:CLAUDE_CONFIG_DIR = "${configDir}"`
    : '    # Using default claude config';

  return `# Claude Wake Script (auto-generated by claude-wake)
# Wakes the PC from sleep, pings Claude to start the usage window,
# then puts the PC back to sleep.

$logFile = "${LOG_PATH.replace(/\\/g, '\\\\')}"
$timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"

Add-Content -Path $logFile -Value "[$timestamp] Waking up and starting Claude..."

try {
${configLine}
    $result = echo "hi" | & "${claudePath.replace(/\\/g, '\\\\')}" -p 2>&1
    $responseText = ($result | Out-String).Trim()
    if (-not $responseText) { $responseText = "(empty)" }
    $timestamp2 = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    Add-Content -Path $logFile -Value "[$timestamp2] OK - Response: $responseText"
} catch {
    $timestamp2 = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    Add-Content -Path $logFile -Value "[$timestamp2] ERROR - $($_.Exception.Message)"
}

Start-Sleep -Seconds 30

$timestamp3 = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
Add-Content -Path $logFile -Value "[$timestamp3] Going back to sleep..."

Add-Type -AssemblyName System.Windows.Forms
[System.Windows.Forms.Application]::SetSuspendState([System.Windows.Forms.PowerState]::Suspend, $true, $false)
`;
}

function runPowershell(script: string): string {
  const tmpFile = path.join(os.tmpdir(), 'claude-wake-tmp.ps1');
  fs.writeFileSync(tmpFile, script, 'utf8');
  try {
    return execSync(`powershell -ExecutionPolicy Bypass -File "${tmpFile}"`, {
      encoding: 'utf8',
      stdio: 'pipe',
    }).trim();
  } finally {
    try { fs.unlinkSync(tmpFile); } catch {}
  }
}

function createScheduledTask(hour: number, minute: number): boolean {
  const timeStr = `${String(hour).padStart(2, '0')}:${String(minute).padStart(2, '0')}`;
  try {
    runPowershell(`
      $action = New-ScheduledTaskAction -Execute 'powershell.exe' -Argument '-ExecutionPolicy Bypass -WindowStyle Hidden -File ${SCRIPT_PATH}'
      $trigger = New-ScheduledTaskTrigger -Daily -At ${timeStr}
      $settings = New-ScheduledTaskSettingsSet -WakeToRun -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries -StartWhenAvailable
      Register-ScheduledTask -TaskName '${TASK_NAME}' -Action $action -Trigger $trigger -Settings $settings -Description 'Claude Wake - Wakes PC and starts Claude session' -Force
    `);
    return true;
  } catch (err: any) {
    console.error('  Error creating scheduled task:', err.message);
    return false;
  }
}

function removeScheduledTask(): boolean {
  try {
    runPowershell(`Unregister-ScheduledTask -TaskName '${TASK_NAME}' -Confirm:$false`);
    return true;
  } catch {
    return false;
  }
}

function getExistingTask(): { time: string; state: string } | null {
  try {
    const result = runPowershell(`
      $t = Get-ScheduledTask -TaskName '${TASK_NAME}' -ErrorAction SilentlyContinue
      if ($t) {
        $sb = $t.Triggers[0].StartBoundary
        Write-Output "$($t.State)|$sb"
      }
    `);

    if (!result) return null;

    const [state, startBoundary] = result.split('|');
    const timeMatch = startBoundary?.match(/T(\d{2}:\d{2})/);
    return { time: timeMatch ? timeMatch[1] : '??:??', state };
  } catch {
    return null;
  }
}

function parseTime(input: string): { hour: number; minute: number } | null {
  const match = input.trim().match(/^(\d{1,2})(?::(\d{2}))?$/);
  if (!match) return null;

  const hour = parseInt(match[1], 10);
  const minute = match[2] ? parseInt(match[2], 10) : 0;

  if (hour < 0 || hour > 23 || minute < 0 || minute > 59) return null;
  return { hour, minute };
}

function showLog() {
  if (!fs.existsSync(LOG_PATH)) {
    console.log('  No logs found yet.');
    return;
  }

  const content = fs.readFileSync(LOG_PATH, 'utf8').trim();
  const lines = content.split('\n');
  const recent = lines.slice(-10);
  console.log('');
  console.log('  Recent log entries:');
  console.log('  ───────────────────');
  recent.forEach(line => console.log(`  ${line}`));
  console.log('');
}

async function selectProfile(): Promise<{ claudePath: string; configDir: string | null; profileName: string }> {
  const claudePath = findClaude();
  const profiles = detectProfiles();

  if (profiles.length === 0) {
    console.log(`  Claude found at: ${claudePath}`);
    console.log('  No profiles detected, using default.');
    return { claudePath, configDir: null, profileName: 'claude (default)' };
  }

  console.log('');
  console.log('  Detected Claude profiles:');
  console.log('');
  profiles.forEach((p, i) => {
    console.log(`  ${i + 1}. ${p.name} (${p.configDir})`);
  });
  console.log('');

  const profileChoice = await ask(`  Which profile to use? (1-${profiles.length}): `);
  const idx = parseInt(profileChoice.trim(), 10) - 1;

  if (idx >= 0 && idx < profiles.length) {
    const selected = profiles[idx];
    console.log(`  Using profile: ${selected.name}`);
    return { claudePath, configDir: selected.configDir, profileName: selected.name };
  }

  console.log('  Invalid choice, using default.');
  return { claudePath, configDir: null, profileName: 'claude (default)' };
}

async function main() {
  banner();

  if (process.platform !== 'win32') {
    console.log('  This tool only works on Windows (uses Task Scheduler).');
    process.exit(1);
  }

  const existing = getExistingTask();
  const savedConfig = loadConfig();

  if (existing) {
    const profileInfo = savedConfig ? ` | Profile: ${savedConfig.profileName}` : '';
    console.log(`  Active schedule: Wake at ${existing.time} (${existing.state}${profileInfo})`);
    console.log('');
  }

  console.log('  What would you like to do?');
  console.log('');
  console.log('  1. Schedule wake time');
  console.log('  2. View execution logs');
  console.log('  3. Remove schedule');
  console.log('  4. Test now (ping Claude without sleeping)');
  console.log('  5. Change profile');
  console.log('  6. Exit');
  console.log('');

  const choice = await ask('  Option: ');

  switch (choice.trim()) {
    case '1': {
      const timeInput = await ask('  What time should your PC wake up? (e.g. 6, 06:00, 5:30): ');
      const time = parseTime(timeInput);

      if (!time) {
        console.log('  Invalid time. Use HH:MM format or just the hour.');
        break;
      }

      const timeFormatted = `${String(time.hour).padStart(2, '0')}:${String(time.minute).padStart(2, '0')}`;
      console.log('');
      console.log(`  Setting up daily wake at ${timeFormatted}...`);

      // Use saved config or ask for profile
      let config = savedConfig;
      if (!config) {
        const profile = await selectProfile();
        config = profile;
        saveConfig(config);
      } else {
        console.log(`  Using saved profile: ${config.profileName}`);
      }

      if (!fs.existsSync(SCRIPTS_DIR)) fs.mkdirSync(SCRIPTS_DIR, { recursive: true });

      const script = generateWakeScript(config.claudePath, config.configDir);
      fs.writeFileSync(SCRIPT_PATH, script, 'utf8');
      console.log(`  Wake script created: ${SCRIPT_PATH}`);

      const ok = createScheduledTask(time.hour, time.minute);
      if (ok) {
        console.log('');
        console.log(`  Done! Your PC will wake up every day at ${timeFormatted},`);
        console.log(`  ping Claude (${config.profileName}) to start your usage window, then go back to sleep.`);
        console.log(`  Logs: ${LOG_PATH}`);
      }
      break;
    }

    case '2': {
      showLog();
      break;
    }

    case '3': {
      const removed = removeScheduledTask();
      if (removed) {
        console.log('  Schedule removed successfully.');
        try { fs.unlinkSync(CONFIG_PATH); } catch {}
      } else {
        console.log('  No schedule found to remove.');
      }
      break;
    }

    case '4': {
      console.log('  Testing Claude...');
      const config = savedConfig || { claudePath: findClaude(), configDir: null, profileName: 'default' };

      try {
        const env = { ...process.env };
        if (config.configDir) env.CLAUDE_CONFIG_DIR = config.configDir;

        const result = execSync(`echo hi | "${config.claudePath}" -p`, {
          encoding: 'utf8',
          env,
          timeout: 60000,
        }).trim();

        console.log(`  Profile: ${config.profileName}`);
        console.log(`  Response: ${result}`);
      } catch (err: any) {
        console.error(`  Error: ${err.message}`);
      }
      break;
    }

    case '5': {
      const profile = await selectProfile();
      saveConfig(profile);
      console.log(`  Profile saved: ${profile.profileName}`);
      console.log('  Run option 1 again to update the schedule with this profile.');
      break;
    }

    case '6':
      break;

    default:
      console.log('  Invalid option.');
  }

  console.log('');
  rl.close();
}

main();
